/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedSettings: typeof import('./../components/AdvancedSettings.vue')['default']
    BuffCoveragePanel: typeof import('./../components/BuffCoveragePanel.vue')['default']
    ChannelSelector: typeof import('./../components/ChannelSelector.vue')['default']
    ChartPanel: typeof import('./../components/ChartPanel.vue')['default']
    DamageItem: typeof import('./../components/DamageItem.vue')['default']
    DebugPanel: typeof import('./../components/DebugPanel.vue')['default']
    DpsChartPanel: typeof import('./../components/DpsChartPanel.vue')['default']
    HistoryChartPanel: typeof import('./../components/HistoryChartPanel.vue')['default']
    NpcapGuideDialog: typeof import('./../components/NpcapGuideDialog.vue')['default']
    PlayerChart: typeof import('./../components/PlayerChart.vue')['default']
    SidebarNav: typeof import('./../components/SidebarNav.vue')['default']
    SkillDetailItem: typeof import('./../components/SkillDetailItem.vue')['default']
    StartupNoticeDialog: typeof import('./../components/StartupNoticeDialog.vue')['default']
    StatusBar: typeof import('./../components/StatusBar.vue')['default']
    TabsPanel: typeof import('./../components/TabsPanel.vue')['default']
    TitleBar: typeof import('./../components/TitleBar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTag: typeof import('vant/es')['Tag']
  }
}
