/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedSettings: typeof import('./../components/AdvancedSettings.vue')['default']
    ChannelSelector: typeof import('./../components/ChannelSelector.vue')['default']
    ChartPanel: typeof import('./../components/ChartPanel.vue')['default']
    DamageItem: typeof import('./../components/DamageItem.vue')['default']
    DebugPanel: typeof import('./../components/DebugPanel.vue')['default']
    StatusBar: typeof import('./../components/StatusBar.vue')['default']
    TabsPanel: typeof import('./../components/TabsPanel.vue')['default']
    TitleBar: typeof import('./../components/TitleBar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
